server:
  port: 5701
spring:
  application:
    name: shtp-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default Bar
      routes:
      - id: shtp-security
        uri: lb://shtp-security
        predicates:
        - Path=/security/**
        filters:
        - StripPrefix=1

      - id: shtp-product
        uri: lb://shtp-product
        predicates:
        - Path=/product/**
        filters:
        - StripPrefix=1

      - id: shtp-message
        uri: lb://shtp-message
        predicates:
        - Path=/message/**
        filters:
        - StripPrefix=1



logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:5501/eureka/
