server:
  port: 5501 #启动端口

spring:
  application:
    name: shtp-eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetcUseregistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
