server:
  port: 5704

spring:
  application:
    name: shtp-message
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/shtp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:5501/eureka/

mybatis:
  config-location: classpath:/mybatis-config.xml
