server:
  port: 5701

spring:
  application:
    name: shtp-member
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/survey
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:5501/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.shtp.member.bean  # 注意：对应实体类的路径