server:
  port: 5701

spring:
  application:
    name: shtp-zuul

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:5501/eureka/
zuul:
  routes:
    security:
      path: /**
      serviceId: shtp-security
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
