server:
  port: 5701

spring:
  application:
    name: shtp-zuul
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/shtp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:5501/eureka/

mybatis:
  config-location: classpath:/mybatis-config.xml

zuul:
  routes:
    product:
      path: /product/**        #表示带有/product前缀的路径（此处为产品服务）
      serviceId: shtp-product  #如果是/product/**路径下的请求，则跳转到shtp-product
    askbuy:
      path: /askbuy/**         #求购服务路径
      serviceId: shtp-askbuy  #如果是/askbuy/**路径下的请求，则跳转到shtp-askbuy
    search:
      path: /search/**         #搜索服务路径
      serviceId: shtp-search  #如果是/search/**路径下的请求，则跳转到shtp-search
